using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VTOLVRControlsMapper
{
    public static class VRControlNames
    {
        public const string Ligth_Nav = "NavLightInteractable";
        public const string Ligth_Strobe = "StrobLightInteractable";
        public const string Ligth_Landing = "LandingLightInteractable";
        public const string Ligth_Instrument = "InsturmentLightInteractable";
        public const string Ligth_Interior = "InteriorLightInteractable";
        public const string Cover_Fuel_Dump = "coverSwitchInteractable_fuelDump";
        public const string Switch_Fuel_Dump = "fuelDumpSwitchInteractable";
        public const string Switch_Fuel_Port = "FuelPort";
        public const string Switch_CATOTrim = "CATOTrimInteractable";
        public const string Switch_Glimit = "GLimitInteractable";
        public const string Switch_SAS_Roll = "RollSASInteractable";
        public const string Switch_SAS_Yaw = "YawSASInteractable";
        public const string Switch_SAS_Pitch = "PitchSASInteractable";
        public const string Switch_SAS_Master = "AssistMasterInteractable";
        public const string Swtich_Flare = "FlareInteractable";
        public const string Swtich_Chaff = "ChaffInteractable";
        public const string Switch_Brake_Lock = "BrakeLockInteractable";
        public const string Switch_Wing = "WingSwitchInteractable";
        public const string Knob_Power_Radar = "RadarPowerInteractable";
        public const string Knob_RWR = "RWRModeInteractable";
        public const string Cover_MasterArm = "coverSwitchInteractable_masterArm";
        public const string Switch_MasterArm = "masterArmSwitchInteractable";
        public const string Knob_Power_MFD1 = "MFD1PowerInteractable";
        public const string Knob_Power_MFD2 = "MFD2PowerInteractable";
        public const string Button_MMFD_Left_Power = "powButtonMMFDLeft";
        public const string Button_MMFD_Right_Power = "powButtonMMFDRight";
        public const string Button_MMFD_Right_Fuel = "fuelButton";
        public const string Button_MMFD_Right_Fuel_Drain = "fuelDrainButton";
        public const string Button_MMFD_Left_RWR = "RWRButton";
        public const string Button_Seat_Lower = "lowerSeatInter";
        public const string Button_Seat_Higher = "raiseSeatInter";
        public const string Button_Jettison_Tanks = "JettTanksInteractable";
        public const string Button_Jettison_Clear = "ClearJettisonInteractable";
        public const string Button_Jettison_Empty = "JettisonEmptyInteractable";
        public const string Button_Jettison_All = "JettisonAllInteractable";
        public const string Cover_Jettison = "coverSwitchInteractable_jettisonButton";
        public const string Button_Jettison_Master = "MasterJettisonButtonInteractable";
        public const string Switch_Hook = "HookInteractable";
        public const string Switch_Hook_Cat = "CatHookInteractable";
        public const string Lever_LandingGear = "GearInteractable";
        public const string Lever_Canopy = "CanopyInteractable";
        public const string Switch_Battery = "mainBattSwitchInteractable";
        public const string Switch_APU = "apuSwitchInteractable";
        public const string Cover_Engine_Right = "coverSwitchInteractable_rightEngine";
        public const string Switch_Engine_Right = "rightEngineSwitchInteractable";
        public const string Cover_Engine_Left = "coverSwitchInteractable_leftEngine";
        public const string Switch_Engine_Left = "leftEngineSwitchInteractable";
        public const string Button_MFD_Swap = "mfdSwapButton";
        public const string Switch_Power_HMCS = "hmcsPowerInteractable";
        public const string Switch_Power_HUD = "hudPowerInteractable";
        public const string Button_AP_Nav = "navAPButton";
        public const string Button_AP_Off = "offAPButton";
        public const string Button_AP_Speed = "speedAPButton";
        public const string Button_AP_Altitude = "altitudeAPButton";
        public const string Button_AP_Heading = "headingAPButton";
        public const string Button_Clear_Waypoint = "ClrWptButton";
        public const string Button_Altitude_Mode = "AltitudeModeInteractable";
        public const string Button_Master_Caution = "MasterCautionInteractable";
        public const string Button_Visor = "visorButtonInteractable";
        public const string Helm_NightVision = "helmNVGInteractable";
        public const string Helm_Visor = "helmVisorInteractable";
        public const string Helm_Visor2 = "helmVisorInteractable2";
        public const string Button_NVG = "nvgButtonInteractable";
        public const string Lever_Eject_Right = "rightSideEjectInteractable";
        public const string Lever_Eject_Left = "sideEjectInteractable";
        public const string Rear_View_Mirror = "canopyFrame.003";
        public const string Button_MFD1_L1 = "MFD1-Button-L1";
        public const string Button_MFD1_L2 = "MFD1-Button-L2";
        public const string Button_MFD1_L3 = "MFD1-Button-L3";
        public const string Button_MFD1_L4 = "MFD1-Button-L4";
        public const string Button_MFD1_L5 = "MFD1-Button-L5";
        public const string Button_MFD1_R1 = "MFD1-Button-R1";
        public const string Button_MFD1_R2 = "MFD1-Button-R2";
        public const string Button_MFD1_R3 = "MFD1-Button-R3";
        public const string Button_MFD1_R4 = "MFD1-Button-R4";
        public const string Button_MFD1_R5 = "MFD1-Button-R5";
        public const string Button_MFD1_T1 = "MFD1-Button-T1";
        public const string Button_MFD1_T2 = "MFD1-Button-T2";
        public const string Button_MFD1_T3 = "MFD1-Button-T3";
        public const string Button_MFD1_T4 = "MFD1-Button-T4";
        public const string Button_MFD1_T5 = "MFD1-Button-T5";
        public const string Button_MFD1_B1 = "MFD1-Button-B1";
        public const string Button_MFD1_B2 = "MFD1-Button-B2";
        public const string Button_MFD1_B3 = "MFD1-Button-B3";
        public const string Button_MFD1_B4 = "MFD1-Button-B4";
        public const string Button_MFD1_B5 = "MFD1-Button-B5";
        public const string Button_MFD2_L1 = "MFD2-Button-L1";
        public const string Button_MFD2_L2 = "MFD2-Button-L2";
        public const string Button_MFD2_L3 = "MFD2-Button-L3";
        public const string Button_MFD2_L4 = "MFD2-Button-L4";
        public const string Button_MFD2_L5 = "MFD2-Button-L5";
        public const string Button_MFD2_R1 = "MFD2-Button-R1";
        public const string Button_MFD2_R2 = "MFD2-Button-R2";
        public const string Button_MFD2_R3 = "MFD2-Button-R3";
        public const string Button_MFD2_R4 = "MFD2-Button-R4";
        public const string Button_MFD2_R5 = "MFD2-Button-R5";
        public const string Button_MFD2_T1 = "MFD2-Button-T1";
        public const string Button_MFD2_T2 = "MFD2-Button-T2";
        public const string Button_MFD2_T3 = "MFD2-Button-T3";
        public const string Button_MFD2_T4 = "MFD2-Button-T4";
        public const string Button_MFD2_T5 = "MFD2-Button-T5";
        public const string Button_MFD2_B1 = "MFD2-Button-B1";
        public const string Button_MFD2_B2 = "MFD2-Button-B2";
        public const string Button_MFD2_B3 = "MFD2-Button-B3";
        public const string Button_MFD2_B4 = "MFD2-Button-B4";
        public const string Button_MFD2_B5 = "MFD2-Button-B5";
    }
}